kind: wasmer.io/App.v0
package: .
owner: test02
app_id: da_KGzIxtmU9N8B
scaling:
  mode: single_concurrency
env:
  DB_HOST: ${{DB_HOST}}
  DB_PORT: ${{DB_PORT}}
  DB_NAME: ${{DB_NAME}}
  DB_USERNAME: ${{DB_USERNAME}}
  DB_PASSWORD: ${{DB_PASSWORD}}
capabilities:
  database:
    engine: mysql
files:
  - '.env'
volumes:
  - name: storage_app
    mount: /app/storage/app
