[dependencies]
"php/php-eh" = "=8.3.404-beta.6"

[fs]
"/app" = "app"

[[command]]
name = "run"
module = "php/php-eh:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "127.0.0.1:8080"]